### ISSUE TITLE
Account resolution not working in offline scenarios

### ISSUE THREAD

**Issue by flobroeder** [fbprogmbh/Audit-Test-Automation#99]
In case domain joined machine is "offline" and not connected to central AD name resolution against Domain Controller leads to an error...
This is expected but could be handled better from perspective of error handling...

![image](https://user-images.githubusercontent.com/23223285/165120864-4791071f-a1c7-4ad7-9098-9374918a7606.png)

Expected behaviour: Prompt an information for domain accounts that at execution time central domain controller was not reachable...

**Comment by qngngyn** [comment]
Fixed with 4c73ee7a6c1e0e23826913f9097fec9780558e96 and 81a4e5326c99cb235ea1a52f1e7ee19aee8d4571

**Comment by TuemmlerKelch** [comment]
This is not solved yet, when the DC is not available for SID -> Name resolution, SBD-10 still fails with error-code 1789.

Please catch this code and make sure to add a note to the report stating that there were SIDs in the group that could not be resolved.

**Comment by SteffenWinternheimer** [comment]
![grafik](https://user-images.githubusercontent.com/35689334/195044986-a1905ded-e5ec-4c96-84c0-9110000848ca.png)

check if this value = true (so a connection is available)

reproducable:
disconnect from internet, run report and check if error message appears

**Comment by qngngyn** [comment]
Source of the problem has been found in the "Get-LocalGroupMember"-Command. It is known to throw "1789" error and "can't compare two values" depending on circumstances that can't be fixed. There has been a workaround put in place that fixes those issues in #158. Therefore this error doesn't appear anymore.
